services:
  backend:
    image: neurodegenvis-backend
    build: backend/
    ports:
      - 8000:8000
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERVER: ${SERVER}

  frontend:
    image: neurodegenvis-frontend
    build: frontend/
    ports:
      - 80:80
